import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import SessionProviderWrapper from "./providers/SessionProviderWrapper";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ShopHub",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0000000a]`}
      >
        <SessionProviderWrapper>
  <div>
    <div className="fixed left-0 right-0 z-20">
      <Navbar />
    </div>

    <main className="min-h-[calc(100vh-240px)] pt-[70px]">{children}</main>
    
    <div>
      <Footer />
    </div>
  </div>
</SessionProviderWrapper>

      </body>
    </html>
  );
}
