import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "ShopHub",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",   // or "/favicon.png"
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0000000a]`}
      >
        <div>
          <Navbar></Navbar>
          
        </div>
        {children}
      </body>
    </html>
  );
}
